### ISSUE TITLE
关于模型选择的问题

### ISSUE THREAD

**Issue by muzhi1991** [yanghh2000/Alirector#1]
感谢作者的工作，请问一下，我看论文里面的只提到了用baichuan做为base模型训练，但是代码里面是有chatglm和qwen的一些设置，请问一下使用不同的基础模型性能差距大嘛？还是选择baichuan有什么特殊的考虑？

**Comment by yanghh2000** [comment]
我们当时主要考虑基座的性能，对比测试起来是baichuan2比较好。当然，现在也出了更强的模型如Yi-1.5、qwen2、glm4等，性能应该会更好

**Comment by yanghh2000** [comment]
> 感谢作者的工作，请问一下，我看论文里面的只提到了用baichuan做为base模型训练，但是代码里面是有chatglm和qwen的一些设置，请问一下使用不同的基础模型性能差距大嘛？还是选择baichuan有什么特殊的考虑？

我们当时主要考虑基座的性能，对比测试起来是baichuan2比较好。当然，现在也出了更强的模型如Yi-1.5、qwen2、glm4等，性能应该会更好

**Comment by muzhi1991** [comment]
> > 感谢作者的工作，请问一下，我看论文里面的只提到了用baichuan做为base模型训练，但是代码里面是有chatglm和qwen的一些设置，请问一下使用不同的基础模型性能差距大嘛？还是选择baichuan有什么特殊的考虑？
> 
> 我们当时主要考虑基座的性能，对比测试起来是baichuan2比较好。当然，现在也出了更强的模型如Yi-1.5、qwen2、glm4等，性能应该会更好

好的，在论文附录里看到ChatGLM3、Yi在NLPCC18-TEST上的对比数据
