### ISSUE TITLE
关于知识蒸馏阶段的问题

### ISSUE THREAD

**Issue by Nephamaster** [yanghh2000/Alirector#2]
问题1：
请问在 native 数据集上进行知识蒸馏时，student 是阶段一训练出的初始纠错模型对吗？
我看论文是这么写的，但代码中似乎是使用 learner 数据集蒸馏好的模型作为 student。

问题2：
论文附录中提供的参数设置 Table 6 中针对 NLPCC2018 和 F/NaCGEC 有不同的 alpha 和 beta 以及 warmup_steps 的值，
请问这是否是指在蒸馏时，对于 native 数据集用 NLPCC2018 那套参数，对 native 数据集用 FCGEC 那套？

**Comment by Nephamaster** [comment]
感谢作者抽出时间阅读我这些浅显的问题，个人感觉读完论文没有完全理解透对于不同的数据集模型训练的策略是怎样的

**Comment by yanghh2000** [comment]
> 问题1： 请问在 native 数据集上进行知识蒸馏时，student 是阶段一训练出的初始纠错模型对吗？ 我看论文是这么写的，但代码中似乎是使用 learner 数据集蒸馏好的模型作为 student。
> 
> 问题2： 论文附录中提供的参数设置 Table 6 中针对 NLPCC2018 和 F/NaCGEC 有不同的 alpha 和 beta 以及 warmup_steps 的值， 请问这是否是指在蒸馏时，对于 native 数据集用 NLPCC2018 那套参数，对 native 数据集用 FCGEC 那套？

A1: 对于FCGEC的训练，因为其训练数据比较少，因此加了learner训练集分两阶段去训。同理，蒸馏训练也是一样，先在learner上蒸馏，然后在FCGEC上训，以此来增加蒸馏训练数据量。

A2: 是的，不同数据集上对应不同的超参。

**Comment by Nephamaster** [comment]
十分感谢您的解答，但我还是有些小疑问：
不同的数据集上对应不同的超参，也就是说对于learner和native的**测试数据集**（NLPCC和F/NaCGEC），我们要分别进行两轮完整的训练（从train_stage1到distill），然后在其对应的测试数据集上进行测试；
还是说不用进行两轮训练，仅是在一轮的对齐和蒸馏中对于learner和native的**训练数据集**采用不同的超参进行训练

**Comment by Nephamaster** [comment]
> > 问题1： 请问在 native 数据集上进行知识蒸馏时，student 是阶段一训练出的初始纠错模型对吗？ 我看论文是这么写的，但代码中似乎是使用 learner 数据集蒸馏好的模型作为 student。
> > 问题2： 论文附录中提供的参数设置 Table 6 中针对 NLPCC2018 和 F/NaCGEC 有不同的 alpha 和 beta 以及 warmup_steps 的值， 请问这是否是指在蒸馏时，对于 native 数据集用 NLPCC2018 那套参数，对 native 数据集用 FCGEC 那套？
> 
> A1: 对于FCGEC的训练，因为其训练数据比较少，因此加了learner训练集分两阶段去训。同理，蒸馏训练也是一样，先在learner上蒸馏，然后在FCGEC上训，以此来增加蒸馏训练数据量。
> 
> A2: 是的，不同数据集上对应不同的超参。

十分感谢您的解答，但我还是有些小疑问：
不同的数据集上对应不同的超参，也就是说对于learner和native的测试数据集（NLPCC和F/NaCGEC），我们要分别进行两轮完整的训练（从train_stage1到distill），然后在其对应的测试数据集上进行测试；
还是说不用进行两轮训练，仅是在一轮的对齐和蒸馏中对于learner和native的训练数据集采用不同的超参进行训练

**Comment by yanghh2000** [comment]
> > > 问题1： 请问在 native 数据集上进行知识蒸馏时，student 是阶段一训练出的初始纠错模型对吗？ 我看论文是这么写的，但代码中似乎是使用 learner 数据集蒸馏好的模型作为 student。
> > > 问题2： 论文附录中提供的参数设置 Table 6 中针对 NLPCC2018 和 F/NaCGEC 有不同的 alpha 和 beta 以及 warmup_steps 的值， 请问这是否是指在蒸馏时，对于 native 数据集用 NLPCC2018 那套参数，对 native 数据集用 FCGEC 那套？
> > 
> > 
> > A1: 对于FCGEC的训练，因为其训练数据比较少，因此加了learner训练集分两阶段去训。同理，蒸馏训练也是一样，先在learner上蒸馏，然后在FCGEC上训，以此来增加蒸馏训练数据量。
> > A2: 是的，不同数据集上对应不同的超参。
> 
> 十分感谢您的解答，但我还是有些小疑问： 不同的数据集上对应不同的超参，也就是说对于learner和native的测试数据集（NLPCC和F/NaCGEC），我们要分别进行两轮完整的训练（从train_stage1到distill），然后在其对应的测试数据集上进行测试； 还是说不用进行两轮训练，仅是在一轮的对齐和蒸馏中对于learner和native的训练数据集采用不同的超参进行训练

没太理解这个问题是什么

**Comment by Nephamaster** [comment]
> > > > 问题1： 请问在 native 数据集上进行知识蒸馏时，student 是阶段一训练出的初始纠错模型对吗？ 我看论文是这么写的，但代码中似乎是使用 learner 数据集蒸馏好的模型作为 student。
> > > > 问题2： 论文附录中提供的参数设置 Table 6 中针对 NLPCC2018 和 F/NaCGEC 有不同的 alpha 和 beta 以及 warmup_steps 的值， 请问这是否是指在蒸馏时，对于 native 数据集用 NLPCC2018 那套参数，对 native 数据集用 FCGEC 那套？
> > > 
> > > 
> > > A1: 对于FCGEC的训练，因为其训练数据比较少，因此加了learner训练集分两阶段去训。同理，蒸馏训练也是一样，先在learner上蒸馏，然后在FCGEC上训，以此来增加蒸馏训练数据量。
> > > A2: 是的，不同数据集上对应不同的超参。
> > 
> > 
> > 十分感谢您的解答，但我还是有些小疑问： 不同的数据集上对应不同的超参，也就是说对于learner和native的测试数据集（NLPCC和F/NaCGEC），我们要分别进行两轮完整的训练（从train_stage1到distill），然后在其对应的测试数据集上进行测试； 还是说不用进行两轮训练，仅是在一轮的对齐和蒸馏中对于learner和native的训练数据集采用不同的超参进行训练
> 
> 没太理解这个问题是什么

就是整个训练过程需要两次吗

**Comment by yanghh2000** [comment]
> > > 问题1： 请问在 native 数据集上进行知识蒸馏时，student 是阶段一训练出的初始纠错模型对吗？ 我看论文是这么写的，但代码中似乎是使用 learner 数据集蒸馏好的模型作为 student。
> > > 问题2： 论文附录中提供的参数设置 Table 6 中针对 NLPCC2018 和 F/NaCGEC 有不同的 alpha 和 beta 以及 warmup_steps 的值， 请问这是否是指在蒸馏时，对于 native 数据集用 NLPCC2018 那套参数，对 native 数据集用 FCGEC 那套？
> > 
> > 
> > A1: 对于FCGEC的训练，因为其训练数据比较少，因此加了learner训练集分两阶段去训。同理，蒸馏训练也是一样，先在learner上蒸馏，然后在FCGEC上训，以此来增加蒸馏训练数据量。
> > A2: 是的，不同数据集上对应不同的超参。
> 
> 十分感谢您的解答，但我还是有些小疑问： 不同的数据集上对应不同的超参，也就是说对于learner和native的测试数据集（NLPCC和F/NaCGEC），我们要分别进行两轮完整的训练（从train_stage1到distill），然后在其对应的测试数据集上进行测试； 还是说不用进行两轮训练，仅是在一轮的对齐和蒸馏中对于learner和native的训练数据集采用不同的超参进行训练

不用两次，训fcgec时直接用在learner上训练过的就行，而且因为分了两个阶段，所以第一个数据集的训练超参对第二个数据集的训练影响不会特别大

**Comment by Nephamaster** [comment]
> > > > 问题1： 请问在 native 数据集上进行知识蒸馏时，student 是阶段一训练出的初始纠错模型对吗？ 我看论文是这么写的，但代码中似乎是使用 learner 数据集蒸馏好的模型作为 student。
> > > > 问题2： 论文附录中提供的参数设置 Table 6 中针对 NLPCC2018 和 F/NaCGEC 有不同的 alpha 和 beta 以及 warmup_steps 的值， 请问这是否是指在蒸馏时，对于 native 数据集用 NLPCC2018 那套参数，对 native 数据集用 FCGEC 那套？
> > > 
> > > 
> > > A1: 对于FCGEC的训练，因为其训练数据比较少，因此加了learner训练集分两阶段去训。同理，蒸馏训练也是一样，先在learner上蒸馏，然后在FCGEC上训，以此来增加蒸馏训练数据量。
> > > A2: 是的，不同数据集上对应不同的超参。
> > 
> > 
> > 十分感谢您的解答，但我还是有些小疑问： 不同的数据集上对应不同的超参，也就是说对于learner和native的测试数据集（NLPCC和F/NaCGEC），我们要分别进行两轮完整的训练（从train_stage1到distill），然后在其对应的测试数据集上进行测试； 还是说不用进行两轮训练，仅是在一轮的对齐和蒸馏中对于learner和native的训练数据集采用不同的超参进行训练
> 
> 不用两次，训fcgec时直接用在learner上训练过的就行，而且因为分了两个阶段，所以第一个数据集的训练超参对第二个数据集的训练影响不会特别大

好的，非常感谢您的耐心解答！！
