### ISSUE TITLE
关于验证集

### ISSUE THREAD

**Issue by hvuehu** [yanghh2000/Alirector#3]
您好，论文中写到CSL训练时的验证集为MuCGEC-Dev，但在代码中stage1和stage2部分，都是分出训练集的一部分作为验证集。请问一下，训练时是如何使用MuCGEC-Dev的？

**Comment by yanghh2000** [comment]
你好，需要把训练脚本中eval_path改成验证集路径，我们实验中发现使用MuCGEC-Dev与否影响不是特别大，所以脚本没有改过来

**Comment by hvuehu** [comment]
> 你好，需要把训练脚本中eval_path改成验证集路径，我们实验中发现使用MuCGEC-Dev与否影响不是特别大，所以脚本没有改过来

好的，感谢~
